

FIREBASE_PROJECT_ID = "fyndassignment"
FIREBASE_PRIVATE_KEY_ID = "c4a18256fb51a1b09ae2439cb3bfa747e2167c8e"
FIREBASE_PRIVATE_KEY = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCgaVgNeaVsU2MX
OxisSd9wroTZ36jwuxkwgOJ225p9rf6yiTJaBjUrO4p1TJZIaUgNhJckDFnJnDuS
QizHmD5ODbVS58Qy+x2xqqMURTQ9l9vGxRcCAfegO2iYyudQ/V9wKQUAe8oyfzMi
lwfF6Yytld9AoKfvWrL3rtJaa68IABAn1Fmg+1WqL6eSQDghuIaPbLwfbtam7Znd
2Upao+97Bt2t6urGRyZdI0I79jfIEP1OZXwapS0k0Dh5xm1KSce7mWQN+bUwLejG
gl26JmUHsPRm0lBQ0DFPhA9CIZMq3Q6r6OiwvA22d/QNcNRYp99TC0+8Z3RGkRd+
bayx6TyjAgMBAAECggEAC7GSPy06f2qWwydGNa0O8k5uldllneLtw6jpmWOJ4BaS
hh5VQtXIA3ZMMh/apr2yCHY9dF3IH9fZSeC0FfrFs/fw23HUziibMgvv5nbjB4ht
94//jOBq1k3uYpEMCs3lqq361N2xUDwQlLlw0h8j57WQuEvd4id4+3BNmlTWRh1p
aK69Um1vm1JIZuqht4sv7vVyL4sstcNGimQBKd2bw2XrcIWihOZ2bNJzLsD1iMcy
/FO9HT0DiulwRBttEgMjoGE8KwtHhE8CDr0jpvSxxqvfTL5BaFGbBzziuo9AuFqY
paZBWLMXbRNOYpuQr3rkWvTOpYPIHVKgpHGbC3smAQKBgQDcyFuLPtNhiiP3kBcC
U1huvA4/WxBk69wkSWyrE9o+U9pa7KlmvRhMt2OyFKhssrtK/DUgVIHNt+HILilf
kiDtKljdoSgeadtsK8rAVOK/Dr9sy1rAvyQtPIwmL+YCN/zyja77eATZaWujYv6s
WQbqrT3pljeFK4tSDWbuXaviAQKBgQC5/7w3GvtlcU/+7YCZb+k3kRCRWBUFF2wA
OIZCa+hIJ2DfHGYxMT0IW57uDKovMXsceHaH0lk8pzSf9NK1fuuLsKIZlHlb2pNp
WrMzL5uKkjbKC8AbLfNRfD1icW0ygBSYhzQc6ge1UtKiLCZfPePIy//X5E8WIuLx
dRXht4xWowKBgQDFx8KiMczAozRnMLA8CBe/Uz3cKaK9FcEmzJPJicZHcWy5aSqz
+4+KIfrwa6sZfN9lZBvfc3S4qhJb9mZf1BMlAnuLRzQeUqwa8fv2YdSiXP7E4kLR
SimJUKUoDF6a/DbfvmbTpQeLD/I58pO8JyCYGEvPNh9Ub9al0ZW00TsKAQKBgQCy
HWL5Bj6uIzeu8XNP/CpCiwlplgbzDD3hbD+txbX3urX6kjCOdQ90PIDSh5BFh0XU
ussPP/EysxAjCYjqQzN/XtOsWVFqE8NMhY3Lu5Bgv6n2DBCYNoWmh6ok5mfij2Kp
ufe+pKJjEoAgytSoKhVCyZAkBz9w/FGFVlFxCJs8rwKBgDIvxesdUEVA+2BfMkIv
EKFztcXK+9vJ6DGvTsMsdyvwT0Ba9/QSh/qHt/70kBwk51juWHczqy+o1ILP/I06
dJp2cBXTvL1AkmWEvNua4qtUjOOvVKU4thoB0EuO26wwLCsxF6ANaag+tuWWq3rm
ic4FvvGp2HDmekS6zv2h1yLp
-----END PRIVATE KEY-----"""
FIREBASE_CLIENT_EMAIL = "firebase-adminsdk-fbsvc@fyndassignment.iam.gserviceaccount.com"
FIREBASE_CLIENT_ID = "111968373809564254280"
GEMINI_API_KEY = "AIzaSyC5LHTbKEXPjxoTXm2UqCoVvl7D36LBWsE"
OPENROUTER_API_KEY = "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"
